openapi: 3.0.3
info:
  title: Pact - consumer-react - LocalFunctionProj
  version: 1.0.0
  contact: {}
servers:
  - url: '{{url}}'
paths:
  /:
    get:
      summary: A request to get a personalised message
      description: A request to get a personalised message
      operationId: aRequestToGetAPersonalisedMessage
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: world
      responses:
        '200':
          description: A request to get a personalised message
          content:
            text/plain:
              examples:
                A request to get a personalised message:
                  value: '"Hello, world. This HTTP triggered function executed successfully."'
tags: []
