name: ConsumerCI

on:
  push:
    branches: ['main', 'frontend*']
    paths:
      - 'consumer-react/**'
  pull_request:
    branches: ['main']
    paths:
      - 'consumer-react/**'

  workflow_dispatch:

env:
  version: ${{ github.sha }}-consumer-react
  PACT_BROKER_BASE_URL: https://saflow.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  environment: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: cd consumer-react && npm ci
      - run: cd consumer-react && npm test
      - uses: pactflow/actions/publish-pact-files@v1.0.1
        env:
          pactfiles: consumer-react/pacts

  deploy:
    strategy:
      matrix:
        environment: [test, production]
      fail-fast: false
    needs: [test]
    runs-on: ubuntu-latest
    env:
      application_name: consumer-react
    steps:
      - name: can-i-deploy ${{ env.application_name }} to ${{ matrix.environment }}
        uses: pactflow/actions/can-i-deploy@v1.0.1
        env:
          to_environment: ${{ matrix.environment }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './consumer-react/build'
          production-branch: main
          production-deploy: false
          alias: test
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      - name: record-deployment ${{ env.application_name }} to ${{ matrix.environment }}
        if: success() && github.ref == 'refs/heads/main'
        uses: pactflow/actions/record-deployment@v1.0.1
        env:
          environment: ${{ matrix.environment }}
